Mensagens:
    Apenas_Jogadores: '&cComando liberado apenas para jogadores'
    
    Terreno:
        jaExiste: 'Este terreno ja existe'
        jaExisteTerrenoProximo: 'Ja existe um terreno proximo a voce, afaste-se e tente novamente'
        comprado: 'Terreno comprado com sucesso!'
        compradoDinheiroSubtraido: 'Foi debitado da sua conta um valor de R$%dinheiro%'
        limiteExcedido: 'Voce nao pode criar mais que %quantidade% terrenos'
        naoeSeu: 'Este terreno nao pertence a você'
        naoEstaOnline: '&cEste jogador nao esta online'
        entradaProibida: '&cVoce nao pode entrar no terreno de %owner%'
        amigoAdicionado: 'Você deu permissao para %player% em seu terreno'
        amigoRemovido: 'Você retirou as permissoes de %player% do seu terreno'
        amigoJaAdicionado: '%player% Ja possui permissoes no seu terreno'
        amigoNaodicionado: '%player% Nao possui permissoes no seu terreno'
        amigoJaAdicionadoEntry: '%player% Ja possui permissoes de entrar em seu terreno'
        amigoNaodicionadoEntry: '%player% Nao possui permissoes de entrar em seu terreno'
        amigoAdicionadoEntry: 'Você deu permissao para %player% entrar em seu terreno'
        amigoRemovidoEntry: 'Você retirou as permissoes de %player% entrar em seu terreno'
        naoeTerreno: 'Utilize este comando dentro de um terreno'
        msgAdicionada: 'Mensagem adicionada ao entrar no terreno'
        msgRemovida: 'Mensagem removida ao entrar no terreno'
        msgAdicionadaEntry: 'Mensagem adicionada ao entrar no terreno sem permissao'
        msgRemovidaEntry: 'Mensagem removida ao entrar no terreno sem permissao'
        msgEntrarDesativado: 'Agora qualquer pessoa pode entrar em seu terreno'
        msgEntrarAtivado: 'Agora somente que voce autorizar pode entrar em seu terreno'
        pvpAtivado: 'Agora o PVP no terreno esta liberado'
        pvpDesativado: 'Agora o PVP no terreno esta proibido'
        spawnmobsAtivado: 'Agora mobs poderão spawnar em seu terreno'
        spawnmobsDesativado: 'Agora nenhum mobs poderá spawnar em seu terreno'
        removido: 'Voce abandonou seu terreno'
        expandido: 'Terreno expandido'
        expandidoMenor: 'Você diminuiu o tamanho do seu terreno'
        expansaoCancel: 'Modo de expansão cancelado'
        expansaoAtiva: 'Selecione um 2 ponto para expandir seu terreno'
        naoTem: 'Não possui nenhum terreno nesta regiao'
        naoExiste: 'Este terreno não existe'
        teleportar: 'Voce foi teleportado ate seu terreno %nome%'
        terrenosLista: 'Voce possui %quantidade% terrenos %nl% &6- &7Seus terrenos: %terrenos%'
        naoTemTerrenos: 'Voce nao possui nenhum terreno ainda'
        mundobloqueado: 'Voce nao pode criar terreno neste mundo'
        info:
            - '&6-----------&8 [&6&lEDTerrenos&8] &6-----------'
            - ''
            - ' &f- &6Terreno: &7%nome%'
            - ' &f- &6Dono: &7%owner%'
            - ''
            - ' &f- &6PVP: &7%pvp%'
            - ' &f- &6Spawnmobs: &7%spawn%'
            - ' &f- &6Mensagem: &7%msg%'
            - ' &f- &6Mensagem entrada proibida: &7%msg2%'
            - ' &f- &6Tamanho: &7%size%'
            - ' &f- &6Amigos: &7%amigos%'
            - ' &f- &6Entrada permitida: &7%ep%'
            - ''
            - '&6-----------&8 [&6&lEDTerrenos&8] &6-----------'
        expandirExplicacao:
            - '&6-----------&8 [&6&lEDTerrenos&8] &6-----------'
            - ''
            - ' &f- &6Tutorial de expansão do terreno'
            - ''
            - ' &f- &6Para expandir seu terreno pegue em sua mão um'
            - ' &f- &6graveto (Stick) e clique em um dos 4 lados'
            - ' &f- &6do seu terreno, logo após clique novamente'
            - ' &f- &6em um novo ponto no mapa ate onde deseja expandir.'
            - ''
            - ' &f- &6Para cancelar o modo de expansão, basta '
            - ' &f- &6Passar o scroll do mouse'
            - ''
            - '&6-----------&8 [&6&lEDTerrenos&8] &6-----------'
    
    UsoCorreto:
        terreno:
            - '&6-----------&8 [&6&lEDTerrenos&8] &6-----------'
            - '&6Utilize &f/terreno &6<argumento>'
            - ''
            - '&f&lArgumentos:'
            - ' &f- &6comprar tamanho nome &7&o- Compra um terreno. R$%dinheiro% por bloco'
            - ' &f- &6vender &7&o- Coloca placa de venda'
            - ' &f- &6abandonar &7&o- Abandona seu terreno '
            - ' &f- &6expandir &7&o- Visualiza o tutorial de como expandir seu terreno'
            - ' &f- &6addamigo player &7&o- Autoriza o jogador editar'
            - ' &f- &6removeamigo player &7&o- Proibe o jogador de editar'
            - ' &f- &6addmsg msg &7&o- Adiciona mensagem de boas vindas ao entrar'
            - ' &f- &6removemsg &7&o- Remove a mensagem de boas vindas'
            - ' &f- &6addmsgentry &7&o- Adiciona mensagem quando jogador nao pode entrar'
            - ' &f- &6removemsgentry &7&o- Remove a mensagem quando jogador nao pode entrar'
            - ' &f- &6entrar on / off &7&o- Autoriza / Proibe jogadores de entrar'
            - ' &f- &6addentrar player &7&o- Autoriza o jogador a entrar'
            - ' &f- &6removeentrar &7&o- Proibe o jogador de entrar'
            - ' &f- &6pvp on / off &7&o- Autoriza / Proibe o PVP'
            - ' &f- &6spawnmobs on / off &7&o- Autoriza / Proibe o spawn de mobs'
            - ' &f- &6info &7&o- Visualiza informações do terreno'
            - ' &f- &6lista &7&o- Visualiza todos os seus terrenos'
            - ' &f- &6teleportar nome &7&o- Teleporta ate o terreno especifico'
            - '&6-----------&8 [&6&lEDTerrenos&8] &6-----------'
        
        addmsg: 'Utilize /terreno addmsg msg'
        addmsgEntry: 'Utilize /terreno addmsggentry msg'
        comprar: 'Utilize /terreno comprar tamanho nome'
        entrar: 'Utilize /terreno entrar on / off'
        pvp: 'Utilize /terreno pvp on / off'
        spawnmobs: 'Utilize /terreno spawnmobs on / off'
        addamigo: 'Utilize /terreno addamigo player'
        removeamigo: 'Utilize /terreno removeamigo player'
        expandir: 'Utilize /terreno expandir tamanho'
        tamanho: 'O tamanho deve ser em numeros inteiros e positivo'
        tamanhoMaximoUltrapassado: 'Voce ultrapassou o limite de tamanho de %tamanhoMax% blocos, o terreno que esta tentando criar possui %tamanho% blocos'
        tamanhoMinimoExigido: 'O terreno deve ter no minimo %tamanhoMin% blocos, o terreno que esta tentando criar possui %tamanho% blocos'
        teleportar: 'Utilize /terreno teleportar nome'
    semDinheiro: 'Você nao possui dinheiro suficiente, é necessario R$%dinheiro%'

Config:
    prefixo: ' &6&lEDTerrenos &7'
    Limite:
        player: 3
        vip: 10
    Tamanho:
        maximo: 2500
        minimo: 100
    valorPorBloco: 50.0
    valorPorBlocoExpansao: 50.0
    mapabloqueado:
        - 'world'
        - 'city'
        - 'loja'
        - 'WarpMobs'
        